version: '2'
services:
    videopoc-app:
        image: videopoc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://videopoc-postgresql:5432/videopoc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videopoc-postgresql:
        extends:
            file: postgresql.yml
            service: videopoc-postgresql
